#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Colors
red='\033[0;31m'
green='\033[0;32m'
no_color='\033[0m'

# Get current branch
curr_branch="$(git rev-parse --abbrev-ref HEAD)"

# Compare branch names.
if [[ "$curr_branch" =~ main ]]; then
	echo ""
	echo -e "${red}You can't commit directly to "$curr_branch".${no_color}"
	echo ""
	exit 2
fi
